[package]
name = "server"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
analytic_engine = { path = "../analytic_engine" }
arrow_deps = { path = "../arrow_deps" }
async-trait = "0.1.53"
avro-rs = "0.13"
catalog = { path = "../catalog" }
ceresdbproto_deps = { path = "../ceresdbproto_deps" }
cluster = { path = "../cluster" }
common_types = { path = "../common_types" }
common_util = { path = "../common_util" }
df_operator = { path = "../df_operator" }
futures = "0.3"
grpcio = { path = "../grpcio" }
http = "0.2"
interpreters = { path = "../interpreters" }
lazy_static = "1.4.0"
log = "0.4"
logger = { path = "../components/logger" }
meta_client = { path = "../meta_client" }
opensrv-mysql = "0.1.0"
profile = { path = "../components/profile" }
protobuf = "2.20"
query_engine = { path = "../query_engine" }
prometheus = "0.12"
prometheus-static-metric = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.60"
snafu = { version ="0.6.10", features = ["backtraces"]}
sql = { path = "../sql" }
system_catalog = { path = "../system_catalog" }
table_engine = { path = "../table_engine" }
tokio = { version = "1.0", features = ["full"] }
twox-hash = "1.6"
warp = "0.3"
bytes = "1.1.0"

[dev-dependencies]
sql = { path = "../sql" , features=["test"]}
