# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
name = "wal"

[package.license]
workspace = true

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies.rocksdb]
git = "https://github.com/tikv/rust-rocksdb.git"
rev = "85e79e52c6ad80b8c547fcb90b3cade64f141fac"
features = ["portable"]
optional = true

[features]
wal-message-queue = ["dep:message_queue"]
wal-table-kv = ["dep:table_kv"]
wal-rocksdb = ["dep:rocksdb"]
wal-local-storage = ["memmap2", "crc32fast"]

[[test]]
name = "read_write"
required-features = ["wal-message-queue", "wal-table-kv", "wal-rocksdb", "wal-local-storage"]

[dependencies]
anyhow = { workspace = true }
async-scoped = { version = "0.9.0", features = ["use-tokio"] }
async-trait = { workspace = true }
bytes_ext = { workspace = true }
chrono = { workspace = true }
codec = { workspace = true }
common_types = { workspace = true }
crc32fast = { version = "1.4.2", optional = true }
futures = { workspace = true, features = ["async-await"], optional = true }
generic_error = { workspace = true }
horaedbproto = { workspace = true }
lazy_static = { workspace = true }
logger = { workspace = true }
macros = { workspace = true }
memmap2 = { version = "0.9.4", optional = true }
message_queue = { workspace = true, optional = true }
prometheus = { workspace = true }
prost = { workspace = true }
rayon = "1.10.0"
runtime = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
size_ext = { workspace = true }
smallvec = { workspace = true }
snafu = { workspace = true }
table_kv = { workspace = true, optional = true }
time_ext = { workspace = true }
timed_task = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
futures = { workspace = true, features = ["async-await"] }
rand = "0.8.5"
tempfile = { workspace = true }
uuid = { version = "1.3", features = ["v4"] }
